# Generated by Django 5.0.3 on 2025-01-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_dislike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='likes',
        ),
    ]
